profiles:
  default:
    prod_buckets: "prod,prd,buckets"
    artifactory:
      snapshot_server: "http://127.0.0.1:5000/artifactory/snapshot/{{application}}/-/{{version}}/{{application}}-{{version}}.tgz"
      release_server: "http://127.0.0.1:5000/artifactory/release/{{application}}/-/{{version}}/{{application}}-{{version}}.tgz"
    snow_broker:
      hostname: 'http://127.0.0.1:5000'
      endpoint:
        incident: incident
        change_record: change/HBO%20Change
    ecs_s3:
      endpoint_url: http://localhost:9000
      region: us-east-1
      access_key_var: s3_local_aws_access_key_id
      secret_key_var: s3_local_aws_secret_access_key

  dev:
    prod_buckets: "prod,prd,prod-bucket"
    artifactory:
      snapshot_server: "http://127.0.0.1:5000-a"
      release_server: "http://127.0.0.1:5000/release/a"
    snow_broker:
      hostname: http://localhost:8080
      endpoint:
        incident: incident
        change_record: change/HBO%20Change
    ecs_s3:
      endpoint_url: http://localhost:9000
      region: us-east-1
      access_key_var: s3_dev_aws_access_key_id
      secret_key_var: s3_dev_aws_secret_access_key

  prod:
    prod_buckets: "prod,prd,prod-bucket"
    artifactory:
      snapshot_server: "http://127.0.0.1:5000/artifactory/{{application}}/-/{{version}}/{{application}}-{{version}}.tgz"
      release_server: "http://127.0.0.1:5000/artifactory/release/{{application}}/-/{{version}}/{{application}}-{{version}}.tgz"
    snow_broker:
      hostname: http://localhost:8080
      endpoint:
        incident: incident
        change_record: change/HBO%20Change
    ecs_s3:
      endpoint_url: http://localhost:9000
      region: us-east-1
      access_key_var: s3_prod_aws_access_key_id
      secret_key_var: s3_prod_aws_secret_access_key
